import type {
  Submission,
  SubmissionWithRelations,
  AIGrade,
  ReviewNote,
  Payment,
  ActivityLog,
} from "./db/types";

// Generate realistic timestamps
const now = new Date();
const daysAgo = (days: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const hoursAgo = (hours: number) => {
  const date = new Date(now);
  date.setHours(date.getHours() - hours);
  return date.toISOString();
};

// CV Versions for orders
export interface CVVersion {
  id: string;
  submission_id: string;
  version_number: number;
  file_path: string;
  file_name: string;
  uploaded_at: string;
  notes?: string;
}

// Dummy CV versions
const cvVersions: Record<string, CVVersion[]> = {
  "order_001": [],
  "order_002": [
    {
      id: "cv_v1_002",
      submission_id: "order_002",
      version_number: 1,
      file_path: "cv-files/order_002_v1.pdf",
      file_name: "marcus_johnson_v1_draft.pdf",
      uploaded_at: daysAgo(1),
      notes: "First draft - improved bullet points",
    },
  ],
  "order_003": [],
  "order_004": [
    {
      id: "cv_v1_004",
      submission_id: "order_004",
      version_number: 1,
      file_path: "cv-files/order_004_v1.pdf",
      file_name: "james_wilson_v1_final.pdf",
      uploaded_at: daysAgo(1),
      notes: "Final version ready for delivery",
    },
  ],
  "order_005": [
    {
      id: "cv_v1_005",
      submission_id: "order_005",
      version_number: 1,
      file_path: "cv-files/order_005_v1.pdf",
      file_name: "priya_patel_v1_draft.pdf",
      uploaded_at: daysAgo(5),
      notes: "First draft",
    },
    {
      id: "cv_v2_005",
      submission_id: "order_005",
      version_number: 2,
      file_path: "cv-files/order_005_v2.pdf",
      file_name: "priya_patel_v2_final.pdf",
      uploaded_at: daysAgo(3),
      notes: "Final version after revision request",
    },
  ],
  "order_006": [],
};

// Order 1: Just received (pending) - Sarah Chen, Tech PM
const order1: SubmissionWithRelations = {
  id: "order_001",
  created_at: hoursAgo(2),
  updated_at: hoursAgo(2),
  status: "pending",
  priority: "normal",
  full_name: "Sarah Chen",
  email: "sarah.chen@techcorp.com",
  linkedin_url: "https://linkedin.com/in/sarahchen",
  industries: ["tech"],
  job_titles: "Senior Product Manager",
  career_stage: "currently_working",
  timeline: "immediately",
  location: "San Francisco, CA",
  current_job_role: "Product Manager at TechCorp Inc. Leading a team of 8 engineers on the mobile app platform. Responsible for roadmap planning and stakeholder management.",
  achievements: "Launched 3 major product features that increased user retention by 25%. Led cross-functional team of 12 to deliver mobile app redesign 2 weeks ahead of schedule. Grew monthly active users from 50K to 200K in 18 months.",
  challenges: ["writing_cv", "recruiter_wants", "getting_calls"],
  additional_context: "Looking to transition to a Senior PM role at a larger tech company. Want to emphasize my data-driven approach and leadership experience.",
  has_cover_letter: "want_help",
  certifications: "PMP, Scrum Master Certified, Google Analytics",
  tools: "Jira, Figma, Amplitude, SQL, Tableau",
  cv_file_path: "cv-files/sarah_chen_original.pdf",
  cover_letter_file_path: null,
  rewritten_cv_path: null,
  assigned_to: null,
  due_date: null,
  completed_at: null,
  delivered_at: null,
  ai_grades: [
    {
      id: "grade_001",
      submission_id: "order_001",
      created_at: hoursAgo(2),
      overall_score: 52,
      label: "Needs Work",
      breakdown: {
        clarity: 55,
        impact_evidence: 45,
        scannability: 60,
        ats_safety: 50,
        first_impression: 50,
      },
      top_issues: [
        "Bullet points lack quantifiable metrics",
        "Summary is generic and doesn't highlight unique value",
        "Skills section buried at bottom of page",
      ],
      detailed_analysis: {
        clarity: "Job descriptions are wordy and hard to scan quickly",
        impactEvidence: "Missing concrete numbers and business outcomes",
        scannability: "Good structure but needs better visual hierarchy",
        atsSafety: "Some keyword gaps for PM roles",
        firstImpression: "Doesn't immediately convey senior-level experience",
      },
      recommendations: [
        "Add specific metrics to each bullet point (%, $, time saved)",
        "Rewrite summary to highlight 3 key differentiators",
        "Move skills section higher and organize by category",
      ],
      raw_response: null,
      admin_verified: false,
      admin_notes: null,
    },
  ],
  review_notes: [],
  payments: [
    {
      id: "pay_001",
      submission_id: "order_001",
      created_at: hoursAgo(2),
      updated_at: hoursAgo(2),
      amount: 3000,
      currency: "usd",
      status: "paid",
      stripe_payment_intent_id: "pi_3QxYz123abc",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_sarah123",
      refund_amount: null,
      refund_reason: null,
      refunded_at: null,
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_001_1",
      created_at: hoursAgo(2),
      submission_id: "order_001",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_001_2",
      created_at: hoursAgo(2),
      submission_id: "order_001",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000, method: "card" },
      actor: "system",
    },
    {
      id: "act_001_3",
      created_at: hoursAgo(2),
      submission_id: "order_001",
      action: "AI Grade completed",
      description: "Score: 52/100 - Needs Work",
      metadata: { score: 52 },
      actor: "system",
    },
  ],
};

// Order 2: In progress - Marcus Johnson, Marketing
const order2: SubmissionWithRelations = {
  id: "order_002",
  created_at: daysAgo(2),
  updated_at: daysAgo(1),
  status: "in_progress",
  priority: "high",
  full_name: "Marcus Johnson",
  email: "marcus.j@gmail.com",
  linkedin_url: "https://linkedin.com/in/marcusjohnson",
  industries: ["marketing"],
  job_titles: "Marketing Director, Head of Growth",
  career_stage: "currently_working",
  timeline: "1_2_months",
  location: "New York, NY",
  current_job_role: "Senior Marketing Manager at BrandCo. Managing $2M annual budget across digital and traditional channels. Team of 5 direct reports.",
  achievements: "Increased brand awareness by 40% through integrated campaigns. Grew social media following from 10K to 150K. Reduced customer acquisition cost by 30% through marketing automation.",
  challenges: ["writing_cv", "explaining_experience"],
  additional_context: "Targeting Director-level roles. Need to show strategic thinking and P&L ownership experience.",
  has_cover_letter: "yes",
  certifications: "Google Ads Certified, HubSpot Marketing",
  tools: "HubSpot, Google Analytics, Salesforce, Adobe Creative Suite",
  cv_file_path: "cv-files/marcus_johnson_original.pdf",
  cover_letter_file_path: "cv-files/marcus_johnson_cover.pdf",
  rewritten_cv_path: null,
  assigned_to: "admin",
  due_date: daysAgo(-1),
  completed_at: null,
  delivered_at: null,
  ai_grades: [
    {
      id: "grade_002",
      submission_id: "order_002",
      created_at: daysAgo(2),
      overall_score: 61,
      label: "Fair",
      breakdown: {
        clarity: 65,
        impact_evidence: 70,
        scannability: 55,
        ats_safety: 60,
        first_impression: 55,
      },
      top_issues: [
        "Too much text - needs tighter editing",
        "Leadership experience not prominent enough",
        "Missing some key marketing director keywords",
      ],
      detailed_analysis: null,
      recommendations: [
        "Condense to 2 pages max",
        "Lead with leadership metrics",
        "Add strategic planning examples",
      ],
      raw_response: null,
      admin_verified: true,
      admin_notes: "Good content, just needs restructuring",
    },
  ],
  review_notes: [
    {
      id: "note_002_1",
      submission_id: "order_002",
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
      note_type: "rewrite_instruction",
      content: "Focus on strategic accomplishments. Highlight P&L responsibility and team leadership. Use CAR format for bullet points.",
      is_pinned: true,
    },
    {
      id: "note_002_2",
      submission_id: "order_002",
      created_at: hoursAgo(6),
      updated_at: hoursAgo(6),
      note_type: "general",
      content: "First draft uploaded. Waiting for review before finalizing.",
      is_pinned: false,
    },
  ],
  payments: [
    {
      id: "pay_002",
      submission_id: "order_002",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      amount: 3000,
      currency: "usd",
      status: "paid",
      stripe_payment_intent_id: "pi_3QxYz456def",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_marcus456",
      refund_amount: null,
      refund_reason: null,
      refunded_at: null,
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_002_1",
      created_at: daysAgo(2),
      submission_id: "order_002",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_002_2",
      created_at: daysAgo(2),
      submission_id: "order_002",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000 },
      actor: "system",
    },
    {
      id: "act_002_3",
      created_at: daysAgo(2),
      submission_id: "order_002",
      action: "AI Grade completed",
      description: "Score: 61/100 - Fair",
      metadata: { score: 61 },
      actor: "system",
    },
    {
      id: "act_002_4",
      created_at: daysAgo(1),
      submission_id: "order_002",
      action: "Status changed",
      description: "Changed from Pending to In Progress",
      metadata: { from: "pending", to: "in_progress" },
      actor: "admin",
    },
    {
      id: "act_002_5",
      created_at: daysAgo(1),
      submission_id: "order_002",
      action: "Note added",
      description: "Rewrite instructions added",
      metadata: { note_type: "rewrite_instruction" },
      actor: "admin",
    },
    {
      id: "act_002_6",
      created_at: daysAgo(1),
      submission_id: "order_002",
      action: "CV uploaded",
      description: "V1 - marcus_johnson_v1_draft.pdf",
      metadata: { version: 1, file_name: "marcus_johnson_v1_draft.pdf" },
      actor: "admin",
    },
  ],
};

// Order 3: Under review with AI grade - Emily Rodriguez, Finance
const order3: SubmissionWithRelations = {
  id: "order_003",
  created_at: daysAgo(3),
  updated_at: daysAgo(2),
  status: "review",
  priority: "normal",
  full_name: "Emily Rodriguez",
  email: "emily.rodriguez@financeplus.com",
  linkedin_url: "https://linkedin.com/in/emilyrodriguez-cfa",
  industries: ["finance"],
  job_titles: "Financial Analyst, Investment Analyst",
  career_stage: "career_switcher",
  timeline: "1_2_months",
  location: "Chicago, IL",
  current_job_role: "Accountant at MidSize Corp. 3 years of experience in financial reporting and analysis. Looking to transition into investment analysis.",
  achievements: "Reduced month-end close time by 2 days through process automation. Identified $500K in cost savings through variance analysis. Built financial models used for 3 successful fundraising rounds.",
  challenges: ["writing_cv", "recruiter_wants", "interview_confidence"],
  additional_context: "Career changer from accounting to finance. Have CFA Level 2 passed. Need to reframe accounting experience for finance roles.",
  has_cover_letter: "want_help",
  certifications: "CFA Level 2 Candidate, CPA",
  tools: "Excel, Bloomberg Terminal, Python, SQL, Power BI",
  cv_file_path: "cv-files/emily_rodriguez_original.pdf",
  cover_letter_file_path: null,
  rewritten_cv_path: null,
  assigned_to: "admin",
  due_date: daysAgo(-2),
  completed_at: null,
  delivered_at: null,
  ai_grades: [
    {
      id: "grade_003",
      submission_id: "order_003",
      created_at: daysAgo(3),
      overall_score: 48,
      label: "Needs Work",
      breakdown: {
        clarity: 50,
        impact_evidence: 55,
        scannability: 45,
        ats_safety: 40,
        first_impression: 50,
      },
      top_issues: [
        "CV reads as accountant, not analyst",
        "Technical skills section needs expansion",
        "Missing key finance/investment keywords",
      ],
      detailed_analysis: {
        clarity: "Experience is clear but framed wrong for target role",
        impactEvidence: "Good numbers but need investment-relevant metrics",
        scannability: "Dense paragraphs need bullet points",
        atsSafety: "Missing critical keywords: DCF, valuation, due diligence",
        firstImpression: "Immediately reads as accounting background",
      },
      recommendations: [
        "Reframe all experience through investment analysis lens",
        "Add financial modeling and valuation projects",
        "Highlight CFA progress prominently at top",
      ],
      raw_response: null,
      admin_verified: false,
      admin_notes: null,
    },
  ],
  review_notes: [
    {
      id: "note_003_1",
      submission_id: "order_003",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      note_type: "prompt",
      content: "Key reframe: Position accounting experience as financial analysis foundation. Emphasize modeling, forecasting, and analytical skills.",
      is_pinned: true,
    },
  ],
  payments: [
    {
      id: "pay_003",
      submission_id: "order_003",
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
      amount: 3000,
      currency: "usd",
      status: "paid",
      stripe_payment_intent_id: "pi_3QxYz789ghi",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_emily789",
      refund_amount: null,
      refund_reason: null,
      refunded_at: null,
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_003_1",
      created_at: daysAgo(3),
      submission_id: "order_003",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_003_2",
      created_at: daysAgo(3),
      submission_id: "order_003",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000 },
      actor: "system",
    },
    {
      id: "act_003_3",
      created_at: daysAgo(3),
      submission_id: "order_003",
      action: "AI Grade completed",
      description: "Score: 48/100 - Needs Work",
      metadata: { score: 48 },
      actor: "system",
    },
    {
      id: "act_003_4",
      created_at: daysAgo(2),
      submission_id: "order_003",
      action: "Status changed",
      description: "Changed from Pending to Under Review",
      metadata: { from: "pending", to: "review" },
      actor: "admin",
    },
    {
      id: "act_003_5",
      created_at: daysAgo(2),
      submission_id: "order_003",
      action: "Note added",
      description: "Reframe strategy noted",
      metadata: { note_type: "prompt" },
      actor: "admin",
    },
  ],
};

// Order 4: Completed, awaiting delivery - James Wilson, Sales
const order4: SubmissionWithRelations = {
  id: "order_004",
  created_at: daysAgo(5),
  updated_at: daysAgo(1),
  status: "completed",
  priority: "urgent",
  full_name: "James Wilson",
  email: "james.wilson@salesforce.com",
  linkedin_url: "https://linkedin.com/in/jameswilson-sales",
  industries: ["sales"],
  job_titles: "Enterprise Account Executive",
  career_stage: "currently_working",
  timeline: "immediately",
  location: "Austin, TX",
  current_job_role: "Senior Account Executive at SaaS Corp. Managing enterprise accounts with $2M+ annual value. Consistently exceeding quota by 120%+.",
  achievements: "Closed largest deal in company history ($1.5M ARR). Built strategic partnerships with 5 Fortune 500 companies. Promoted twice in 3 years.",
  challenges: ["getting_calls", "all_above"],
  additional_context: "Looking for VP of Sales or Enterprise AE role at a growth-stage startup. Need to show I can build, not just execute.",
  has_cover_letter: "no",
  certifications: "Salesforce Certified, MEDDIC Trained",
  tools: "Salesforce, Outreach, Gong, LinkedIn Sales Navigator",
  cv_file_path: "cv-files/james_wilson_original.pdf",
  cover_letter_file_path: null,
  rewritten_cv_path: "cv-files/james_wilson_v1_final.pdf",
  assigned_to: "admin",
  due_date: daysAgo(2),
  completed_at: daysAgo(1),
  delivered_at: null,
  ai_grades: [
    {
      id: "grade_004",
      submission_id: "order_004",
      created_at: daysAgo(5),
      overall_score: 68,
      label: "Good",
      breakdown: {
        clarity: 70,
        impact_evidence: 80,
        scannability: 65,
        ats_safety: 60,
        first_impression: 65,
      },
      top_issues: [
        "Strong numbers but buried in text",
        "Missing leadership/team-building examples",
        "Could better highlight strategic thinking",
      ],
      detailed_analysis: null,
      recommendations: [
        "Lead with quota attainment and deal sizes",
        "Add team mentoring and process improvement examples",
        "Include market expansion or territory growth stories",
      ],
      raw_response: null,
      admin_verified: true,
      admin_notes: "Great raw material to work with",
    },
  ],
  review_notes: [
    {
      id: "note_004_1",
      submission_id: "order_004",
      created_at: daysAgo(4),
      updated_at: daysAgo(4),
      note_type: "rewrite_instruction",
      content: "Position for VP-level roles. Highlight: 1) Revenue impact, 2) Team leadership, 3) Strategic account planning. Use STAR format.",
      is_pinned: true,
    },
    {
      id: "note_004_2",
      submission_id: "order_004",
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
      note_type: "general",
      content: "Final version complete. Ready for delivery. Strong transformation - much better positioning for VP roles.",
      is_pinned: false,
    },
  ],
  payments: [
    {
      id: "pay_004",
      submission_id: "order_004",
      created_at: daysAgo(5),
      updated_at: daysAgo(5),
      amount: 3000,
      currency: "usd",
      status: "paid",
      stripe_payment_intent_id: "pi_3QxYz012jkl",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_james012",
      refund_amount: null,
      refund_reason: null,
      refunded_at: null,
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_004_1",
      created_at: daysAgo(5),
      submission_id: "order_004",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_004_2",
      created_at: daysAgo(5),
      submission_id: "order_004",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000 },
      actor: "system",
    },
    {
      id: "act_004_3",
      created_at: daysAgo(5),
      submission_id: "order_004",
      action: "AI Grade completed",
      description: "Score: 68/100 - Good",
      metadata: { score: 68 },
      actor: "system",
    },
    {
      id: "act_004_4",
      created_at: daysAgo(4),
      submission_id: "order_004",
      action: "Status changed",
      description: "Changed from Pending to In Progress",
      metadata: { from: "pending", to: "in_progress" },
      actor: "admin",
    },
    {
      id: "act_004_5",
      created_at: daysAgo(4),
      submission_id: "order_004",
      action: "Priority changed",
      description: "Changed from Normal to Urgent",
      metadata: { from: "normal", to: "urgent" },
      actor: "admin",
    },
    {
      id: "act_004_6",
      created_at: daysAgo(1),
      submission_id: "order_004",
      action: "CV uploaded",
      description: "V1 - james_wilson_v1_final.pdf (Final)",
      metadata: { version: 1, file_name: "james_wilson_v1_final.pdf" },
      actor: "admin",
    },
    {
      id: "act_004_7",
      created_at: daysAgo(1),
      submission_id: "order_004",
      action: "Status changed",
      description: "Changed from In Progress to Completed",
      metadata: { from: "in_progress", to: "completed" },
      actor: "admin",
    },
  ],
};

// Order 5: Delivered with V1 + V2 - Priya Patel, Data Analytics
const order5: SubmissionWithRelations = {
  id: "order_005",
  created_at: daysAgo(7),
  updated_at: daysAgo(3),
  status: "delivered",
  priority: "normal",
  full_name: "Priya Patel",
  email: "priya.patel@datatech.io",
  linkedin_url: "https://linkedin.com/in/priyapatel-data",
  industries: ["data_analytics", "tech"],
  job_titles: "Senior Data Analyst, Analytics Manager",
  career_stage: "currently_working",
  timeline: "3_4_months",
  location: "Seattle, WA",
  current_job_role: "Data Analyst at DataTech. Building dashboards and insights for product team. Managing data pipeline for 10M+ daily events.",
  achievements: "Created executive dashboard used by C-suite for weekly decisions. Reduced data processing time by 60% through pipeline optimization. Trained 15 team members on SQL and Tableau.",
  challenges: ["writing_cv", "recruiter_wants"],
  additional_context: "Want to move into a management role. Have informal leadership experience but need to show it on paper.",
  has_cover_letter: "no",
  certifications: "Google Data Analytics, Tableau Desktop Specialist",
  tools: "Python, SQL, Tableau, Power BI, dbt, Snowflake, Airflow",
  cv_file_path: "cv-files/priya_patel_original.pdf",
  cover_letter_file_path: null,
  rewritten_cv_path: "cv-files/priya_patel_v2_final.pdf",
  assigned_to: "admin",
  due_date: daysAgo(4),
  completed_at: daysAgo(4),
  delivered_at: daysAgo(3),
  ai_grades: [
    {
      id: "grade_005",
      submission_id: "order_005",
      created_at: daysAgo(7),
      overall_score: 58,
      label: "Fair",
      breakdown: {
        clarity: 60,
        impact_evidence: 65,
        scannability: 55,
        ats_safety: 55,
        first_impression: 55,
      },
      top_issues: [
        "Technical skills dominate, soft skills missing",
        "Leadership experience not highlighted",
        "Projects lack business context",
      ],
      detailed_analysis: null,
      recommendations: [
        "Add leadership and mentoring examples",
        "Connect technical work to business outcomes",
        "Include stakeholder management experience",
      ],
      raw_response: null,
      admin_verified: true,
      admin_notes: null,
    },
  ],
  review_notes: [
    {
      id: "note_005_1",
      submission_id: "order_005",
      created_at: daysAgo(6),
      updated_at: daysAgo(6),
      note_type: "rewrite_instruction",
      content: "Emphasize leadership: team training, cross-functional collaboration, stakeholder management. Keep technical depth but add business impact.",
      is_pinned: true,
    },
    {
      id: "note_005_2",
      submission_id: "order_005",
      created_at: daysAgo(4),
      updated_at: daysAgo(4),
      note_type: "general",
      content: "Customer requested revision - wanted more emphasis on Python and ML skills. Updated in V2.",
      is_pinned: false,
    },
  ],
  payments: [
    {
      id: "pay_005",
      submission_id: "order_005",
      created_at: daysAgo(7),
      updated_at: daysAgo(7),
      amount: 3000,
      currency: "usd",
      status: "paid",
      stripe_payment_intent_id: "pi_3QxYz345mno",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_priya345",
      refund_amount: null,
      refund_reason: null,
      refunded_at: null,
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_005_1",
      created_at: daysAgo(7),
      submission_id: "order_005",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_005_2",
      created_at: daysAgo(7),
      submission_id: "order_005",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000 },
      actor: "system",
    },
    {
      id: "act_005_3",
      created_at: daysAgo(7),
      submission_id: "order_005",
      action: "AI Grade completed",
      description: "Score: 58/100 - Fair",
      metadata: { score: 58 },
      actor: "system",
    },
    {
      id: "act_005_4",
      created_at: daysAgo(6),
      submission_id: "order_005",
      action: "Status changed",
      description: "Changed from Pending to In Progress",
      metadata: { from: "pending", to: "in_progress" },
      actor: "admin",
    },
    {
      id: "act_005_5",
      created_at: daysAgo(5),
      submission_id: "order_005",
      action: "CV uploaded",
      description: "V1 - priya_patel_v1_draft.pdf",
      metadata: { version: 1, file_name: "priya_patel_v1_draft.pdf" },
      actor: "admin",
    },
    {
      id: "act_005_6",
      created_at: daysAgo(4),
      submission_id: "order_005",
      action: "Revision requested",
      description: "Customer requested more emphasis on Python/ML",
      metadata: {},
      actor: "customer",
    },
    {
      id: "act_005_7",
      created_at: daysAgo(3),
      submission_id: "order_005",
      action: "CV uploaded",
      description: "V2 - priya_patel_v2_final.pdf (Final)",
      metadata: { version: 2, file_name: "priya_patel_v2_final.pdf" },
      actor: "admin",
    },
    {
      id: "act_005_8",
      created_at: daysAgo(3),
      submission_id: "order_005",
      action: "Status changed",
      description: "Changed from In Progress to Delivered",
      metadata: { from: "in_progress", to: "delivered" },
      actor: "admin",
    },
    {
      id: "act_005_9",
      created_at: daysAgo(3),
      submission_id: "order_005",
      action: "CV delivered",
      description: "Final CV sent to customer via email",
      metadata: {},
      actor: "admin",
    },
  ],
};

// Order 6: Refunded - Alex Thompson
const order6: SubmissionWithRelations = {
  id: "order_006",
  created_at: daysAgo(10),
  updated_at: daysAgo(8),
  status: "refunded",
  priority: "normal",
  full_name: "Alex Thompson",
  email: "alex.thompson@email.com",
  linkedin_url: null,
  industries: ["other"],
  job_titles: "General Manager",
  career_stage: "career_switcher",
  timeline: "exploring",
  location: "Denver, CO",
  current_job_role: "Store Manager at Retail Corp. Managing team of 20+ employees. Responsible for $5M annual revenue.",
  achievements: "Increased store revenue by 15% year-over-year. Reduced employee turnover by 25%. Implemented new inventory system.",
  challenges: ["all_above"],
  additional_context: "Looking to transition out of retail into corporate role. Not sure exactly what I want to do yet.",
  has_cover_letter: "no",
  certifications: null,
  tools: "Microsoft Office, POS Systems",
  cv_file_path: "cv-files/alex_thompson_original.pdf",
  cover_letter_file_path: null,
  rewritten_cv_path: null,
  assigned_to: null,
  due_date: null,
  completed_at: null,
  delivered_at: null,
  ai_grades: [
    {
      id: "grade_006",
      submission_id: "order_006",
      created_at: daysAgo(10),
      overall_score: 42,
      label: "Needs Major Work",
      breakdown: {
        clarity: 45,
        impact_evidence: 50,
        scannability: 40,
        ats_safety: 35,
        first_impression: 40,
      },
      top_issues: [
        "No clear target role defined",
        "Experience not positioned for corporate transition",
        "Missing transferable skills framing",
      ],
      detailed_analysis: null,
      recommendations: [
        "Define specific target roles",
        "Reframe retail management as corporate-relevant experience",
        "Highlight P&L, team leadership, and operational excellence",
      ],
      raw_response: null,
      admin_verified: false,
      admin_notes: null,
    },
  ],
  review_notes: [],
  payments: [
    {
      id: "pay_006",
      submission_id: "order_006",
      created_at: daysAgo(10),
      updated_at: daysAgo(8),
      amount: 3000,
      currency: "usd",
      status: "refunded",
      stripe_payment_intent_id: "pi_3QxYz678pqr",
      stripe_checkout_session_id: null,
      stripe_customer_id: "cus_alex678",
      refund_amount: 3000,
      refund_reason: "Customer decided to postpone job search",
      refunded_at: daysAgo(8),
      metadata: {},
    },
  ],
  activity_log: [
    {
      id: "act_006_1",
      created_at: daysAgo(10),
      submission_id: "order_006",
      action: "Order submitted",
      description: "New CV rewrite order received",
      metadata: {},
      actor: "system",
    },
    {
      id: "act_006_2",
      created_at: daysAgo(10),
      submission_id: "order_006",
      action: "Payment received",
      description: "$30.00 payment processed",
      metadata: { amount: 3000 },
      actor: "system",
    },
    {
      id: "act_006_3",
      created_at: daysAgo(10),
      submission_id: "order_006",
      action: "AI Grade completed",
      description: "Score: 42/100 - Needs Major Work",
      metadata: { score: 42 },
      actor: "system",
    },
    {
      id: "act_006_4",
      created_at: daysAgo(8),
      submission_id: "order_006",
      action: "Refund requested",
      description: "Customer requested refund - postponing job search",
      metadata: {},
      actor: "customer",
    },
    {
      id: "act_006_5",
      created_at: daysAgo(8),
      submission_id: "order_006",
      action: "Refund processed",
      description: "$30.00 refunded to original payment method",
      metadata: { amount: 3000, reason: "Customer decided to postpone job search" },
      actor: "admin",
    },
    {
      id: "act_006_6",
      created_at: daysAgo(8),
      submission_id: "order_006",
      action: "Status changed",
      description: "Changed from Pending to Refunded",
      metadata: { from: "pending", to: "refunded" },
      actor: "admin",
    },
  ],
};

// All dummy orders
const dummyOrders: SubmissionWithRelations[] = [
  order1,
  order2,
  order3,
  order4,
  order5,
  order6,
];

// Export functions
export function getDummyOrders(): SubmissionWithRelations[] {
  return dummyOrders;
}

export function getDummyOrderById(id: string): SubmissionWithRelations | undefined {
  return dummyOrders.find((order) => order.id === id);
}

export function getCVVersions(orderId: string): CVVersion[] {
  return cvVersions[orderId] || [];
}

// Helper to get base submission without relations
export function getDummySubmissions(): Submission[] {
  return dummyOrders.map(({ ai_grades, review_notes, payments, activity_log, ...submission }) => submission);
}
